# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='slug',
            field=models.SlugField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
