# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='slug',
            field=models.SlugField(verbose_name='Atalho'),
        ),
    ]
