# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_livro_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('sobrenome', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('senha', models.CharField(max_length=40, verbose_name='senha')),
            ],
        ),
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
