# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-26 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_livro_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
